#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
Render ansible inventory + vault from the Azure VM provisioned by az_up.sh.

Reads:
    .secrets/azure/last-vm.json   (produced by scripts/az_up.sh)

Writes:
    ansible/inventory/prod.ini
    ansible/group_vars/vpn/vault.yml       (then ansible-vault encrypted)

Vault password resolution order:
    1. $ANSIBLE_VAULT_PASSWORD_FILE
    2. ~/.vault-pass
    3. .secrets/.vault-pass                (auto-generated if missing)

LE email resolution order:
    1. $LE_EMAIL
    2. `git config user.email` (must be set and look like a real email)

Usage:
    scripts/az_configure.py
    scripts/az_configure.py --force        # clobber an existing encrypted vault
"""
from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import uuid
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
LAST_VM = REPO_ROOT / ".secrets" / "azure" / "last-vm.json"
VAULT_PASS_LOCAL = REPO_ROOT / ".secrets" / ".vault-pass"
INVENTORY = REPO_ROOT / "ansible" / "inventory" / "prod.ini"
VAULT_FILE = REPO_ROOT / "ansible" / "group_vars" / "vpn" / "vault.yml"


def die(msg: str) -> None:
    print(f"[az-configure] ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def log(msg: str) -> None:
    print(f"[az-configure] {msg}", file=sys.stderr)


def resolve_vault_pass_file() -> Path:
    env = os.environ.get("ANSIBLE_VAULT_PASSWORD_FILE")
    if env and Path(env).expanduser().is_file():
        return Path(env).expanduser()

    home_pass = Path.home() / ".vault-pass"
    if home_pass.is_file():
        return home_pass

    if VAULT_PASS_LOCAL.is_file():
        return VAULT_PASS_LOCAL

    VAULT_PASS_LOCAL.parent.mkdir(parents=True, exist_ok=True)
    VAULT_PASS_LOCAL.write_text(secrets.token_hex(32) + "\n")
    VAULT_PASS_LOCAL.chmod(0o600)
    log(f"Generated fresh vault password at {VAULT_PASS_LOCAL} (keep it, or delete to regenerate)")
    return VAULT_PASS_LOCAL


_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


def resolve_le_email() -> str:
    env = os.environ.get("LE_EMAIL", "").strip()
    if env:
        if not _EMAIL_RE.match(env):
            die(f"LE_EMAIL={env!r} does not look like an email address")
        return env

    try:
        out = subprocess.run(
            ["git", "config", "--get", "user.email"],
            capture_output=True,
            text=True,
            check=False,
            cwd=REPO_ROOT,
        )
    except FileNotFoundError:
        die("git not on PATH and LE_EMAIL not set — can't determine Let's Encrypt email")

    email = out.stdout.strip()
    if not email or not _EMAIL_RE.match(email) or "example.com" in email:
        die(
            "Could not resolve a real email for Let's Encrypt. "
            "Set LE_EMAIL=you@example.org, or configure git user.email."
        )
    return email


def load_vm() -> dict:
    if not LAST_VM.is_file():
        die(f"{LAST_VM} not found — run `just az-up` first")
    data = json.loads(LAST_VM.read_text())
    for key in ("fqdn", "admin_user"):
        if not data.get(key):
            die(f"{LAST_VM} missing required field: {key}")
    return data


def write_inventory(vm: dict) -> None:
    INVENTORY.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "; Auto-generated by scripts/az_configure.py — safe to re-run.\n"
        "; prod.ini is gitignored (see .gitignore).\n"
        "\n"
        "[vpn]\n"
        f"azure ansible_host={vm['fqdn']} ansible_user={vm['admin_user']}\n"
        "\n"
        "[vpn:vars]\n"
    )
    ssh_key = vm.get("ssh_key")
    if ssh_key:
        content += f"ansible_ssh_private_key_file={ssh_key}\n"
        content += f"ansible_private_key_file={ssh_key}\n"
    INVENTORY.write_text(content)
    log(f"Wrote {INVENTORY.relative_to(REPO_ROOT)}")


def vault_is_encrypted(path: Path) -> bool:
    if not path.is_file():
        return False
    with path.open("rb") as fh:
        head = fh.read(64)
    return head.startswith(b"$ANSIBLE_VAULT;")


def write_vault(vm: dict, email: str, vault_pass_file: Path, force: bool) -> None:
    if vault_is_encrypted(VAULT_FILE) and not force:
        die(
            f"{VAULT_FILE.relative_to(REPO_ROOT)} is already ansible-vault encrypted. "
            "Pass --force to overwrite with a fresh UUID / FQDN."
        )

    if not shutil.which("ansible-vault"):
        die("ansible-vault not on PATH — install ansible-core")

    v2ray_uuid = str(uuid.uuid4())

    VAULT_FILE.parent.mkdir(parents=True, exist_ok=True)
    plaintext = (
        "---\n"
        "# Auto-generated by scripts/az_configure.py. Re-run az-configure to rotate.\n"
        f"vault_domain: {vm['fqdn']}\n"
        f"vault_letsencrypt_email: {email}\n"
        f'vault_v2ray_uuid: "{v2ray_uuid}"\n'
    )
    VAULT_FILE.write_text(plaintext)
    VAULT_FILE.chmod(0o600)

    # Scrub ANSIBLE_VAULT_PASSWORD_FILE from the subprocess env so ansible-vault
    # doesn't see two "default" vault IDs (env + --vault-password-file) and bail
    # with "Specify the vault-id to encrypt with --encrypt-vault-id".
    env = {k: v for k, v in os.environ.items() if k != "ANSIBLE_VAULT_PASSWORD_FILE"}
    subprocess.run(
        ["ansible-vault", "encrypt", "--vault-password-file", str(vault_pass_file), str(VAULT_FILE)],
        check=True,
        env=env,
    )
    log(f"Wrote + encrypted {VAULT_FILE.relative_to(REPO_ROOT)}")
    log(f"  vault_domain            = {vm['fqdn']}")
    log(f"  vault_letsencrypt_email = {email}")
    log(f"  vault_v2ray_uuid        = {v2ray_uuid}")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0] if __doc__ else "")
    p.add_argument("--force", action="store_true", help="Overwrite an existing encrypted vault.yml")
    args = p.parse_args()

    vm = load_vm()
    email = resolve_le_email()
    vault_pass_file = resolve_vault_pass_file()

    write_inventory(vm)
    write_vault(vm, email, vault_pass_file, force=args.force)

    log("")
    log("Vault password file (export for ansible):")
    log(f"  export ANSIBLE_VAULT_PASSWORD_FILE={vault_pass_file}")
    log("")
    log("Next: just deploy && DOMAIN=" + vm["fqdn"] + " just verify")
    return 0


if __name__ == "__main__":
    sys.exit(main())
