services:
  clash:
    build: .
    container_name: clash
    network_mode: host
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    restart: unless-stopped

  dashboard:
    image: haishanh/yacd
    container_name: yacd
    ports:
      - "1234:80"  # Expose YACD on port 1234
    depends_on:
      - clash
    restart: unless-stoppe
